# Generated by Django 4.0.5 on 2024-04-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
